version: "3.8"

services:

  tomcat:
   image: techforum/tomcat-extended:latest
   container_name: tomcat

   ports:
     - 8080:8080

   volumes:
     - ./helloword-host-mounted.war:/usr/local/tomcat/webapps/helloword-host-mounted.war
